<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Group</name>
   <tag></tag>
   <elementGuidId>7c1fee44-a1d0-42f5-a610-7526de8a0b27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LeftNavBar_I0i0_T</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LeftNavBar_I0i0_T']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;User Group&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>278de3d7-5ffb-41eb-966d-a50c104138c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxnb-link </value>
      <webElementGuid>f86e2b33-2244-4e66-a8c4-d167f0976d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CSIS/Admin/UserGroup/Index</value>
      <webElementGuid>2e2e95b5-6a27-4ba9-bb06-4b032f287aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>TargetIFrame</value>
      <webElementGuid>c6d1f2c2-a332-4f16-95a6-3ccffde2d72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LeftNavBar_I0i0_T</value>
      <webElementGuid>351ff4aa-d444-49c4-bad9-f3bb4d85a0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Group</value>
      <webElementGuid>c6fd0cf4-1b44-4e92-914c-529670595bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LeftNavBar_I0i0_T&quot;)</value>
      <webElementGuid>6b5ea8f1-5ff4-4ccc-b46e-b0088584e137</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LeftNavBar_I0i0_T']</value>
      <webElementGuid>8c675c55-86c4-4f5f-a6be-6f6cff92ad87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='LeftNavBar_I0i0_']/a</value>
      <webElementGuid>5ba34fd3-a23d-476f-a76d-3a47bef652f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATION'])[2]/following::a[1]</value>
      <webElementGuid>77451574-f3b9-41d2-9f8e-fc6ffe11483e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATION'])[1]/following::a[1]</value>
      <webElementGuid>edcedbd0-b181-438f-860b-d9d960df0fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::a[1]</value>
      <webElementGuid>6eaa6270-7505-4a02-83bb-9aa94e43f9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CSIS/Admin/UserGroup/Index')]</value>
      <webElementGuid>8c0fbb81-2d4d-4e37-8c9e-69a43d72d2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>b6f713e5-ad1c-416c-9c99-4df970e08f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/CSIS/Admin/UserGroup/Index' and @id = 'LeftNavBar_I0i0_T' and (text() = 'User Group' or . = 'User Group')]</value>
      <webElementGuid>944164d3-771e-4cb2-8e69-1d316baf2b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
