<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Laporan Taksasi_TargetIFrame</name>
   <tag></tag>
   <elementGuidId>8e76b402-4ff8-4896-8173-31898538c424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentSplitter_1_CC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ContentSplitter_1_CC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;TargetIFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>993ec2fd-2b2a-43f7-8aad-7d9b18ebec40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47382a14-9d29-4839-8135-bd969cedd4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentSplitter_1_CC</value>
      <webElementGuid>a5dbf709-3b3f-4ae8-9064-3bf192b5f844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TargetIFrame</value>
      <webElementGuid>831cbfb1-d692-4138-be3a-f3d73875bc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>57117f4a-6b3c-490f-9ebb-06a5de21a6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CSIS/Home/FirstPage</value>
      <webElementGuid>32a71c22-f854-4856-af41-5616e37a2c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6613347b-8f05-4bfb-940e-34cb2f74dedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxsplIF</value>
      <webElementGuid>fa4684a9-0e43-4d98-9492-b92e67b71c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentSplitter_1_CC&quot;)</value>
      <webElementGuid>16454218-4a3f-4db2-af17-93b4a0d42394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ContentSplitter_1_CC']</value>
      <webElementGuid>b4e18ac7-3628-42dd-adc6-7c69b6a201de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ContentSplitter_1']/div/iframe</value>
      <webElementGuid>08f8de49-6718-40ee-8fc5-fea4655cb73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>af884ba7-0349-4b78-8ea8-0f80c0b501c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ContentSplitter_1_CC' and @name = 'TargetIFrame' and @src = '/CSIS/Home/FirstPage']</value>
      <webElementGuid>128d528c-c052-4938-8efc-7666a876030b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
