<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Period Date_dePeriodFrom_B-1Img</name>
   <tag></tag>
   <elementGuidId>55b272f0-b5f5-4717-b297-ebeff3809829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dePeriodFrom_B-1Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='dePeriodFrom_B-1Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Period Date v&quot;s] >> internal:attr=[alt=&quot;v&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>049be6c2-f2a2-40a0-8521-62e494fdbcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dePeriodFrom_B-1Img</value>
      <webElementGuid>a7873732-2a3c-492f-ac1d-a787fdc9ea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_MetropolisBlue</value>
      <webElementGuid>a47b4394-7c8a-4133-abfe-7b3cb21849e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CSIS/DXR.axd?r=1_36-uSlOq</value>
      <webElementGuid>154318d1-e5f3-45ee-bf25-a103c25a03b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>2de1d987-a56b-45b5-91b8-1ecc965fa778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dePeriodFrom_B-1Img&quot;)</value>
      <webElementGuid>d57f2e71-3d28-4cee-92f8-5cc4eaee178b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Laporan Taksasi_TargetIFrame</value>
      <webElementGuid>003d1b6d-4c35-4045-b59d-10beb7d72689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='dePeriodFrom_B-1Img']</value>
      <webElementGuid>9907d73a-b718-4222-9b26-89e609ca9076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dePeriodFrom_B-1']/img</value>
      <webElementGuid>552eade3-24e6-47c3-aa5b-42c8ae7a7f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='v']</value>
      <webElementGuid>5e32b9c6-4ee2-4be9-a168-ed74f5a2c2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>140282db-9cf2-439a-97bb-429690783e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'dePeriodFrom_B-1Img' and @src = '/CSIS/DXR.axd?r=1_36-uSlOq' and @alt = 'v']</value>
      <webElementGuid>0051ee51-048f-40ab-8f50-45d59c8967d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
