<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_-_dePeriodTo_B-1Img</name>
   <tag></tag>
   <elementGuidId>898ac29b-69f5-4690-8b3d-3260784cbc09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dePeriodTo_B-1Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='dePeriodTo_B-1Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;v&quot;s] >> internal:attr=[alt=&quot;v&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bf78ad5f-cb11-42e0-a956-965d6d89e4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dePeriodTo_B-1Img</value>
      <webElementGuid>73b953a4-e727-4e99-b1ce-4f5bd15ed54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_MetropolisBlue</value>
      <webElementGuid>d0162f09-1aa5-4044-af1c-135cff481a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CSIS/DXR.axd?r=1_36-uSlOq</value>
      <webElementGuid>0cedc606-528c-466b-a71e-764fa54d4cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>be866c08-c240-4e9b-a9ac-49c59bc1ba2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dePeriodTo_B-1Img&quot;)</value>
      <webElementGuid>ebde393b-2b25-4899-bdca-0640d7ab5bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Laporan Taksasi_TargetIFrame</value>
      <webElementGuid>f92e31e2-61b5-4677-88d4-58734095d772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='dePeriodTo_B-1Img']</value>
      <webElementGuid>062bc277-7c97-433f-9608-7c0ee6c46c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dePeriodTo_B-1']/img</value>
      <webElementGuid>5ae81fc7-c4e3-4762-99d2-eef77bb852ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='v'])[2]</value>
      <webElementGuid>b88b5ce9-daf6-4140-b995-7f27b71e1416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/table/tbody/tr/td[2]/img</value>
      <webElementGuid>34141169-5218-4523-8e77-031b2323c438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'dePeriodTo_B-1Img' and @src = '/CSIS/DXR.axd?r=1_36-uSlOq' and @alt = 'v']</value>
      <webElementGuid>f4c4ee1a-d534-4656-a818-13cfd35cbf99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
