<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_gvListOfUserGroupDXFREditorcol1</name>
   <tag></tag>
   <elementGuidId>1f14aab5-1452-43db-b2d8-a8fc03b10556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvListOfUserGroup_DXFREditorcol1_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvListOfUserGroup_DXFREditorcol1_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvListOfUserGroup_DXFREditorcol1_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75ae7614-f2cf-4397-8e67-b15bd04af9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_MetropolisBlue dxeEditAreaSys dxh0</value>
      <webElementGuid>dbd62bef-e783-40ce-8d49-218de0f682da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvListOfUserGroup_DXFREditorcol1_I</value>
      <webElementGuid>85f31b8b-2a18-44f9-a8eb-bdf9ab0d0636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvListOfUserGroup$DXFREditorcol1</value>
      <webElementGuid>b186e001-c61c-4369-939c-21fc1422279d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('gvListOfUserGroup_DXFREditorcol1')</value>
      <webElementGuid>2f2f34ec-e98b-4e78-8fed-cae0675a4cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('gvListOfUserGroup_DXFREditorcol1')</value>
      <webElementGuid>c7aa06fc-e4da-4377-b646-11576c348d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('gvListOfUserGroup_DXFREditorcol1')</value>
      <webElementGuid>c948ea90-70d4-4fcb-8879-d11450ad4ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30a084bf-a941-4713-897b-fd5e752f087c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvListOfUserGroup_DXFREditorcol1_I&quot;)</value>
      <webElementGuid>1e6695ca-ea0b-4b20-bf94-55c453d8e252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Laporan Taksasi_TargetIFrame</value>
      <webElementGuid>79919aea-77b7-4f39-b201-555993d29c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvListOfUserGroup_DXFREditorcol1_I']</value>
      <webElementGuid>602e3fe1-5489-475f-be48-9e3b609a6241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvListOfUserGroup_DXFREditorcol1']/tbody/tr/td/input</value>
      <webElementGuid>9485404f-d686-4475-809c-bdf00af33ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/table/tbody/tr/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>e2caec03-21d3-4da9-8dd7-aea9b2b13b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvListOfUserGroup_DXFREditorcol1_I' and @name = 'gvListOfUserGroup$DXFREditorcol1' and @type = 'text']</value>
      <webElementGuid>de399cc4-6fb9-4ed6-8920-37c4b88bd8c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
