<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_gvListOfUserGroupDXFREditorcol3</name>
   <tag></tag>
   <elementGuidId>1e054860-620b-462f-a813-5fd699363a33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvListOfUserGroup_DXFREditorcol3_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvListOfUserGroup_DXFREditorcol3_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvListOfUserGroup_DXFREditorcol3_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30e41d64-9784-4849-90d6-c11d8664f26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_MetropolisBlue dxeEditAreaSys dxh0</value>
      <webElementGuid>347540cd-3c76-4869-b0ff-9d0167e38436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvListOfUserGroup_DXFREditorcol3_I</value>
      <webElementGuid>3704e431-b1d2-4858-b843-b0b4d8665b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvListOfUserGroup$DXFREditorcol3</value>
      <webElementGuid>5bb30af3-9ac3-4fe6-a911-6af1592dc040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('gvListOfUserGroup_DXFREditorcol3')</value>
      <webElementGuid>c3877ddb-e002-410e-bd65-448addb6dfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('gvListOfUserGroup_DXFREditorcol3')</value>
      <webElementGuid>cb85b3ea-4af1-4f31-91b7-2e0f969b2254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('gvListOfUserGroup_DXFREditorcol3')</value>
      <webElementGuid>7dd2115c-ae05-4ab7-b95a-51f75bf52dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>249d4170-641b-431c-a6f5-d4b38df06aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvListOfUserGroup_DXFREditorcol3_I&quot;)</value>
      <webElementGuid>f1548720-5518-4fcf-913a-2161c8380e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Laporan Taksasi_TargetIFrame</value>
      <webElementGuid>d15b846c-802e-4e4f-9fc0-65a4e33f4aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvListOfUserGroup_DXFREditorcol3_I']</value>
      <webElementGuid>84826354-df69-479e-9192-0ecaaef136db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvListOfUserGroup_DXFREditorcol3']/tbody/tr/td/input</value>
      <webElementGuid>c63ce7f8-d1da-40e6-9e61-c22257e549a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>de0d250c-ffe6-41e7-b192-5db3360546ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvListOfUserGroup_DXFREditorcol3_I' and @name = 'gvListOfUserGroup$DXFREditorcol3' and @type = 'text']</value>
      <webElementGuid>f70ff573-cc52-422d-a74b-e3b8480715f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
