<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_gvListOfUserGroupDXFREditorcol0</name>
   <tag></tag>
   <elementGuidId>8d2729c7-dda2-4c59-bf7c-e9c9f227e092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvListOfUserGroup_DXFREditorcol0_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvListOfUserGroup_DXFREditorcol0_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvListOfUserGroup_DXFREditorcol0_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2da8dc26-3bd4-48f8-b499-a7cd11aaede2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_MetropolisBlue dxeEditAreaSys dxh0</value>
      <webElementGuid>0a8ceb70-09d7-43bb-b54a-79fb83c9aa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvListOfUserGroup_DXFREditorcol0_I</value>
      <webElementGuid>7ed0433b-8b8c-4fb6-9327-b69fe42906ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvListOfUserGroup$DXFREditorcol0</value>
      <webElementGuid>2052f891-8cd3-431e-a6b4-e29c16c1534d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('gvListOfUserGroup_DXFREditorcol0')</value>
      <webElementGuid>a82c8280-e4c0-43d9-a74d-edbbd147a6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('gvListOfUserGroup_DXFREditorcol0')</value>
      <webElementGuid>76f4cf55-d725-451d-a770-b2a3efee864d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('gvListOfUserGroup_DXFREditorcol0')</value>
      <webElementGuid>aa5107ef-4637-472d-8c58-cd62bde5048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf91e1ba-dcf8-452a-8969-38d5f25ef632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvListOfUserGroup_DXFREditorcol0_I&quot;)</value>
      <webElementGuid>5affbfec-a345-4fc0-aeff-d0c5386ff112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Laporan Taksasi_TargetIFrame</value>
      <webElementGuid>f3c99544-3ffa-4257-bb5d-2d851ff06513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvListOfUserGroup_DXFREditorcol0_I']</value>
      <webElementGuid>e28c889c-d687-4da7-a630-2d4ea6839572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvListOfUserGroup_DXFREditorcol0']/tbody/tr/td/input</value>
      <webElementGuid>865fac07-e5e7-4d66-a9de-9fbccdb797cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>e6ac9375-1b89-42f0-8aba-da0f4ebc05c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvListOfUserGroup_DXFREditorcol0_I' and @name = 'gvListOfUserGroup$DXFREditorcol0' and @type = 'text']</value>
      <webElementGuid>9397a379-8c4e-4eb5-9211-0b42d6335134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
