<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_User Group</name>
   <tag></tag>
   <elementGuidId>11baa58c-4a04-40ac-90c4-76bc4186388a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LeftNavBar_I0i0_T > span.dx-vam</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LeftNavBar_I0i0_T']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;User Group&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e879236f-a478-487c-a08f-7d7900041a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-vam</value>
      <webElementGuid>b217d653-2f89-436b-ad54-af2e57aaa284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Group</value>
      <webElementGuid>a6db994b-072e-49d6-9d8d-94f3a4d5c5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LeftNavBar_I0i0_T&quot;)/span[@class=&quot;dx-vam&quot;]</value>
      <webElementGuid>05c3bc8b-7a79-45cf-af7c-e5f45dbfa472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='LeftNavBar_I0i0_T']/span</value>
      <webElementGuid>3cbfdc40-3b96-4454-8d29-c80e7e347744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATION'])[2]/following::span[1]</value>
      <webElementGuid>76bd65c8-be85-4755-9e62-4eaf34a04986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATION'])[1]/following::span[2]</value>
      <webElementGuid>5cd2249d-a325-4b75-ba61-fdc145542d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::span[1]</value>
      <webElementGuid>e12c7cf8-0b3b-440a-8326-f90d1aa339b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Security Administrator'])[1]/preceding::span[2]</value>
      <webElementGuid>a51fd5e3-234e-4744-bc0b-964cc5f1ec93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Group']/parent::*</value>
      <webElementGuid>57967d11-6ac7-4dad-846c-1596ad7b06cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>3488cc8c-58ef-43f4-a244-e83bb0814344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'User Group' or . = 'User Group')]</value>
      <webElementGuid>a264cc20-640b-470f-9abe-4d802d85089e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
