<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Today</name>
   <tag></tag>
   <elementGuidId>0beed4bd-52f4-4996-88a9-244282224220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dePeriodFrom_DDD_C_BT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dePeriodFrom_DDD_C_BT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Today&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d46e9143-0529-478c-a446-d158a2f1b208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dePeriodFrom_DDD_C_BT</value>
      <webElementGuid>6987f6c6-1020-487b-9719-cdd0c65b07bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeCalendarButton_MetropolisBlue dxeCalendarButtonHover_MetropolisBlue</value>
      <webElementGuid>ccf0c469-17e1-482e-943a-7a89499df078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ASPx.CalTodayClick('dePeriodFrom_DDD_C');</value>
      <webElementGuid>4277ebd1-9abd-4665-ae0a-e423c2f4a267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>861f52c8-da32-4415-9815-936f6a3e7d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dePeriodFrom_DDD_C_BT&quot;)</value>
      <webElementGuid>71369d80-21db-4770-9fb5-cb77b1b76d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Laporan Taksasi_TargetIFrame</value>
      <webElementGuid>575a451c-28fd-4bdd-8de4-c48e0fdbd31a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='dePeriodFrom_DDD_C_BT']</value>
      <webElementGuid>52fce5fb-429c-4a0a-8b1b-55835e0b28bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dePeriodFrom_DDD_C']/tbody/tr[2]/td/table/tbody/tr/td</value>
      <webElementGuid>2161d564-5de4-4a82-80f1-f18e2382d1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::td[50]</value>
      <webElementGuid>d54a3e20-3f37-42ae-96d6-197f53b97721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::td[51]</value>
      <webElementGuid>057ac00a-8112-47dd-8a86-97945d4d131a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::td[2]</value>
      <webElementGuid>f41cd012-0033-411f-8943-4d5579f2f8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/preceding::td[3]</value>
      <webElementGuid>303ab5cd-2e82-4074-ac11-8cf116559da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>5cf53cb8-cbcf-45a4-a97a-439d851c57ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td</value>
      <webElementGuid>3d3beec9-cf58-4630-8450-89c45dd1ef6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'dePeriodFrom_DDD_C_BT' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>225b3bb1-d353-4438-adac-98fe9fc02c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
