<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Today_1</name>
   <tag></tag>
   <elementGuidId>85b1659f-2b24-4bcf-826e-5c9d0409792b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dePeriodTo_DDD_C_BT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dePeriodTo_DDD_C_BT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Today&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b07cff93-0808-4c4a-a104-62883c4f5439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dePeriodTo_DDD_C_BT</value>
      <webElementGuid>c85840d6-b284-42a8-bbc2-874f3f68dbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeCalendarButton_MetropolisBlue dxeCalendarButtonHover_MetropolisBlue</value>
      <webElementGuid>e17c8cea-4a51-4430-862f-8f09d2e542a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ASPx.CalTodayClick('dePeriodTo_DDD_C');</value>
      <webElementGuid>60fb7a39-7a05-417c-97a9-4347b318781e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>904de133-9cd0-4e55-930e-7b2053f0b5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dePeriodTo_DDD_C_BT&quot;)</value>
      <webElementGuid>e4c939d8-5534-4412-b621-37e9089c07f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Laporan Taksasi_TargetIFrame</value>
      <webElementGuid>5c90a2c6-a03c-4a03-a970-723c4d6edb7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='dePeriodTo_DDD_C_BT']</value>
      <webElementGuid>3daa1f9a-52e4-46c2-87db-e5a79999149e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dePeriodTo_DDD_C']/tbody/tr[2]/td/table/tbody/tr/td</value>
      <webElementGuid>23ca71ff-a114-4161-81eb-be39feebcdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[2]/following::td[50]</value>
      <webElementGuid>0a4d68fc-a945-4677-92e7-dbec0e58987a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[2]/following::td[51]</value>
      <webElementGuid>7a62fa77-8229-4b37-974f-a61320dbe193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[2]/preceding::td[2]</value>
      <webElementGuid>b50abf97-b2eb-45bd-9f0a-23d10e8ef07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[2]/preceding::td[3]</value>
      <webElementGuid>753d82ad-9c0d-4a66-9624-e1b1f75a2b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/div/div/div/div/table[2]/tbody/tr[2]/td/table/tbody/tr/td</value>
      <webElementGuid>2bd272aa-4a13-4a1d-ba4e-6a074c72b43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'dePeriodTo_DDD_C_BT' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>0a33d560-719c-43ec-9089-79203aa9f862</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
