<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_tbPassword</name>
   <tag></tag>
   <elementGuidId>2a3b58b4-51a5-4cde-8ec7-a871eeb1c1ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbPassword_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tbPassword_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9712a4a5-ab94-4d88-9ecf-87a2068aa908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_MetropolisBlue dxeEditAreaSys</value>
      <webElementGuid>8e2cbcf9-ba51-4366-8814-038c49e02a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbPassword_I</value>
      <webElementGuid>15a1f31f-9d81-42dc-a046-e43f6b66735c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tbPassword</value>
      <webElementGuid>1275f0f7-c14f-4cb4-90f8-6b83e36dd15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('tbPassword')</value>
      <webElementGuid>401be7e9-efa6-4b2c-9d06-4932a41ac916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('tbPassword')</value>
      <webElementGuid>c72a7860-827f-4927-9b22-a5e4f17cd506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('tbPassword')</value>
      <webElementGuid>87d364b7-215d-446a-b191-76a5d38405a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c246b938-94a4-4ad3-930c-d4e8f10f7c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbPassword_I&quot;)</value>
      <webElementGuid>7f03e112-59dc-46dc-872a-54cbd6ea0f81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tbPassword_I']</value>
      <webElementGuid>99141590-0722-4722-8562-9b2b1c306e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbPassword']/tbody/tr/td/input</value>
      <webElementGuid>d714e369-1921-4198-ab12-af610d0d99de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>7ea924fa-ef93-4793-be0d-5a699cba6fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tbPassword_I' and @name = 'tbPassword' and @type = 'password']</value>
      <webElementGuid>e7a87fa9-89ba-4e24-a3e9-33dc06e92fb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
