<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User ID_tbUserID</name>
   <tag></tag>
   <elementGuidId>a40db45f-6204-47f6-89fe-b98dd59d9c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbUserID_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tbUserID_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;User ID&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9c470b9-039a-4b29-9c54-96bb75564737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_MetropolisBlue dxeEditAreaSys dxh0</value>
      <webElementGuid>dc69a37e-8ea1-4467-9762-4692c7467e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbUserID_I</value>
      <webElementGuid>557ec8df-0f46-4154-b2f1-e1e28280a1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tbUserID</value>
      <webElementGuid>063be0ca-ab86-482c-898c-7661c833e8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>ASPx.EGotFocus('tbUserID')</value>
      <webElementGuid>6860bb74-022a-40c2-94ee-1f097e9adc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ASPx.ELostFocus('tbUserID')</value>
      <webElementGuid>f780a489-184c-4bdc-8353-0d3c74230165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.EValueChanged('tbUserID')</value>
      <webElementGuid>5c11020f-0df5-430e-a0f1-d8d86de2ed74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66d1ac5b-6941-4988-aa34-0d3103773e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbUserID_I&quot;)</value>
      <webElementGuid>fe8499f4-5bac-48f3-80f2-3af66e9c6ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tbUserID_I']</value>
      <webElementGuid>5ee371e3-26f6-411d-9b5e-f11ad6f60d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbUserID']/tbody/tr/td/input</value>
      <webElementGuid>63aaee58-2378-4c35-8fad-2ac5ac237318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>a2508cc0-07fc-449e-9b5a-6ae7cf564bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tbUserID_I' and @name = 'tbUserID' and @type = 'text']</value>
      <webElementGuid>c6894e6e-5752-4df6-84fb-b463624986e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
